src/WebUI/Areas/Cadastros/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Interfaces;
using Application.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace WebUI.Areas.Cadastros.Controllers
{
    [Area("Cadastros")]
    public class ClientesController : Controller
    {

        private readonly IApplicationCliente _applicationCliente;

        public ClientesController(IApplicationCliente applicationCliente)
        {
            _applicationCliente = applicationCliente;
        } //constructor

        public IActionResult Index()
        {
            return View();
        } //Index


        public JsonResult ListagemClientesJson()
        {
            var lista = _applicationCliente.GetAll();
            //var lista = new { { email = "teste@teste.com"} };
            var settings = new JsonSerializerSettings();
            return Json(lista, settings);
        } //ListagemClientesJson

    } //class

} //namespace

src/WebUI/Areas/Cadastros/Controllers/FornecedoresController.cs
using Application.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace WebUI.Areas.Cadastros.Controllers
{
    [Area("Cadastros")]
    public class FornecedoresController : Controller
    {

        private readonly IApplicationFornecedor _applicationFornecedor;

        public FornecedoresController(IApplicationFornecedor applicationFornecedor)
        {
            _applicationFornecedor = applicationFornecedor;
        } //constructor

        public IActionResult Index()
        {
            return View();
        } //Index

        public JsonResult ListagemFornecedoresJson()
        {
            var lista = _applicationFornecedor.GetAll();
            var settings = new JsonSerializerSettings();
            return Json(lista, settings);
        } //ListagemFornecedorsJson

    } //class
} //namespace

src/WebUI/Areas/Cadastros/Controllers/ProdutosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace WebUI.Areas.Cadastros.Controllers
{

    [Area("Cadastros")]
    public class ProdutosController : Controller
    {
        private readonly IApplicationProduto _applicationProduto;

        public ProdutosController(IApplicationProduto applicationProduto)
        {
            _applicationProduto = applicationProduto;
        } //constructor

        public IActionResult Index()
        {
            return View();
        } //Index

        public JsonResult ListagemProdutosJson()
        {
            var lista = _applicationProduto.GetAll();
            var settings = new JsonSerializerSettings();
            return Json(lista, settings);
        } //ListagemProdutosJson

    } //class

} //namespace

src/WebUI/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace WebUI.Controllers
{
    public class DefaultController : Controller
    {
        public IActionResult Index()
        {
            return View();
        } //Index

        public IActionResult Privacy()
        {
            return View();
        } //Privacy

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            //return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
            return View();
        } //Error


    } //class

} //namespace

src/WebUI/Areas/Cadastros/Views/Clientes/Index.cshtml
@model IEnumerable<Application.ViewModels.ClienteViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apelido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CpfCnpj)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Endereco)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Bairro)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cidade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UF)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CEP)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apelido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CpfCnpj)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Endereco)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Bairro)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cidade)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UF)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CEP)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

src/WebUI/Areas/Cadastros/Views/Fornecedores/Index.cshtml
@{
    ViewData["Title"] = "Fornecedores";
}

<partial name="_Aguarde" />

<br />

<div class="row">
    <div class="col-md-12">
        <a asp-area="Cadastros" asp-controller="Fornecedores" asp-action="Create" class="btn btn-primary"><i class="fas fa-plus"></i> Create New</a>
    </div>
</div>

<hr />

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">Fornecedores</div>
            <div class="card-body" style="overflow-x: auto">

                <table id="tbgrid" class="table table-hover table-bordered" style="width: 100%">
                    <thead>
                        <tr>

                            <th class="no-sort"></th>
                            <th class="no-sort"></th>
                            <th class="text-center">Id</th>
                            <th class="text-center">Apelido</th>
                            <th class="text-center">Nome</th>
                            <th class="text-center">CPF/CNPJ</th>

                            <th class="text-center">E-Mail</th>
                        </tr>
                    </thead>
                </table>


            </div>
        </div>
    </div>
</div>



@section Scripts {

    <script type="text/javascript">

        colunas = [
            {
                "data": "Id",
                "searchable": false,
                "sortable": false,
                "width": "2%",
                "sClass": "text-center",
                "render": function (id) {
                    return "<a href='#' class='btn btn-primary btn-sm showhint' title='Alterar registro'><i class='fas fa-pencil-alt'></a>"
                }
            },
            {
                "data": "Id",
                "searchable": false,
                "sortable": false,
                "width": "2%",
                "sClass": "text-center",
                "render": function (id) {
                    return "<a href='#' class='btn btn-danger btn-sm showhint' title='Excluir registro'><i class='fas fa-trash-alt'></a>"
                }
            },
            {
                "data": "Id",
                "width": "2%",
                "sClass": "text-center"
            },
            {
                "data": "Apelido",
                "width": "28%",
                "sClass": "text-left"
            },
            {
                "data": "Nome",
                "width": "40%",
                "sClass": "text-left"
            },
            {
                "data": "CpfCnpj",
                "width": "16%",
                "sClass": "text-left"
            },
            {
                "data": "Email",
                "width": "20%",
                "sClass": "text-left"
            }
        ];

        $(document).ready(function () {
            ListagemConsulta("tbgrid", urlFornecedores, colunas);
        });

    </script>

}

src/WebUI/Areas/Cadastros/Views/Produtos/Index.cshtml
@{
    ViewData["Title"] = "Produtos";
}

<partial name="_Aguarde" />

<br />

<div class="row">
    <div class="col-md-12">
        <a asp-area="Cadastros" asp-controller="Produtos" asp-action="Create" class="btn btn-primary"><i class="fas fa-plus"></i> Create New</a>
    </div>
</div>

<hr />

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">Produtos</div>
            <div class="card-body" style="overflow-x: auto">

                <table id="tbgrid" class="table table-hover table-bordered" style="width: 100%">
                    <thead>
                        <tr>

                            <th class="no-sort"></th>
                            <th class="no-sort"></th>
                            <th class="text-center">Id</th>
                            <th class="text-center">Apelido</th>
                            <th class="text-center">Nome</th>
                            <th class="text-center">Valor</th>
                            <th class="text-center">Unidade</th>
                            <th class="text-center">Fornecedor</th>
                        </tr>
                    </thead>
                </table>


            </div>
        </div>
    </div>
</div>



@section Scripts {

    <script type="text/javascript">

        colunas = [
            {
                "data": "Id",
                "searchable": false,
                "sortable": false,
                "width": "2%",
                "sClass": "text-center",
                "render": function (id) {
                    return "<a href='#' class='btn btn-primary btn-sm showhint' title='Alterar registro'><i class='fas fa-pencil-alt'></a>"
                }
            },
            {
                "data": "Id",
                "searchable": false,
                "sortable": false,
                "width": "2%",
                "sClass": "text-center",
                "render": function (id) {
                    return "<a href='#' class='btn btn-danger btn-sm showhint' title='Excluir registro'><i class='fas fa-trash-alt'></a>"
                }
            },
            {
                "data": "Id",
                "width": "2%",
                "sClass": "text-center"
            },
            {
                "data": "Apelido",
                "width": "24%",
                "sClass": "text-left"
            },
            {
                "data": "Nome",
                "width": "40%",
                "sClass": "text-left"
            },
            {
                "data": "Valor",
                "width": "10%",
                "sType": "currency",
                "sClass": "text-left"
            },
            {
                "data": "NomeFornecedor",
                "width": "18%",
                "sClass": "text-left"
            }

        ];

        $(document).ready(function () {
            ListagemConsulta("tbgrid", urlProdutos, colunas);
        });

    </script>

}

src/WebUI/Views/Default/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

src/WebUI/Views/Shared/ConstantesJS.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<script type="text/javascript">
    var urlClientes = '@Url.Action("ListagemClientesJson", "Clientes", new { area = "Cadastros"})';
    var urlFornecedores = '@Url.Action("ListagemFornecedoresJson", "Fornecedores", new { area = "Cadastros"})';
    var urlProdutos = '@Url.Action("ListagemProdutosJson", "Produtos", new { area = "Cadastros"})';
    var urlPedidos = '@Url.Action("ListagemPedidosJson", "Pedidos", new { area = "Pedidos"})';
</script>

src/WebUI/Views/Shared/_Aguarde.cshtml
<div id="aguarde" class="modal fade" role="dialog" tabindex="-1" aria-labelledby="myModelLabel" aria-hidden="true" data-keyboard="false" data-backdrop="static">
  <div class="modal-dialog modal-sm">
      <img src="~/images/aguarde.gif" />
  </div>
</div>

src/WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.6/css/buttons.dataTables.min.css" />
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css" />
</head>
<body>

    @Html.Partial("ConstantesJS")

    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Default" asp-action="Index">Logo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Default" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Cadastros" asp-controller="Clientes" asp-action="Index">Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Cadastros" asp-controller="Fornecedores" asp-action="Index">Fornecedores</a>
                        </li>
                        <li>
                            <a class="nav-link text-dark" asp-area="Cadastros" asp-controller="Produtos" asp-action="Index">Produtos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - <a asp-area="" asp-controller="Default" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <!--Table scripts-->
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.print.min.js"></script>
    <!--End Table Scripts-->
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>